name: gpuvmem-cudatoolkit-env
channels:
- pkgw-forge
- conda-forge
- nvidia
- defaults
dependencies:
- casacore
- cfitsio
- cuda-toolkit
- cuda-samples
- openmpi
- python=3.8
- numpy=1.23
- pip
- pip:
  - almatasks==1.5.2
  - casadata==2022.9.5
  - casampi==0.5.01
  - casaplotms==1.8.7
  - casaplotserver==1.4.6
  - casashell==6.5.2.26
  - casatasks==6.5.2.26
  - casatestutils==6.5.2.26
  - casatools==6.5.2.26
  - casaviewer==1.6.6
