name: gpuvmem-cudatoolkit-env
channels:
- pkgw-forge
- conda-forge
- nvidia
- defaults
dependencies:
- casacore
- cfitsio
- cuda-toolkit
- cuda-samples
- openmpi
- mpi4py
- python=3.8
- numpy=1.23
- pip
- pip:
  - almatasks==1.6.1
  - casadata==2023.4.10
  - casafeather==0.0.18
  - casampi==0.5.3
  - casaplotms==2.0.1
  - casaplotserver==1.5.1
  - casashell==6.5.5.21
  - casatasks==6.5.5.21
  - casatestutils==6.5.5.21
  - casatools==6.5.5.21
  - casaviewer==1.7.1
