name: gpuvmem-cudatoolkit-env
channels:
- pkgw-forge
- conda-forge
- nvidia
- defaults
dependencies:
- casacore
- cfitsio
- cuda-toolkit
- cuda-samples
- openmpi
- mpi4py
- python=3.10
- numpy=1.24
- pip
- pip:
  - casadata==2023.9.18
  - casafeather==0.0.20
  - casalogger==1.0.17
  - casampi==0.5.4
  - casaplotms==2.2.4
  - casaplotserver==1.7.1
  - casashell==6.6.0.20
  - casatablebrowser==0.0.33
  - casatasks==6.6.0.20
  - casatestutils==6.6.0.20
  - casatools==6.6.0.20
  - casaviewer==1.9.1
