name: gpuvmem-cudatoolkit-env
channels:
- pkgw-forge
- conda-forge
- nvidia
- defaults
dependencies:
- casacore
- cfitsio
- cuda-toolkit
- cuda-samples
- openmpi
- mpi4py
- python=3.10
- numpy=1.24
- pip
- pip:
  - casatools==6.6.4.34
  - casatasks==6.6.4.34
  - casaplotms==2.4.3
  - casaviewer==2.1.4
  - casashell==6.6.4.34
  - casaplotserver==1.8.2
  - casatestutils==6.6.4.34
  - casatablebrowser==0.0.35
  - casalogger==1.0.19
  - casafeather==0.0.22
  - casampi==0.5.5
